language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  - XDEBUG_MODE=coverage

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 8.0

before_script:
  - composer self-update
  - |
    if [ $(phpenv version-name) != '8.0' ]; then
      travis_retry composer update
    fi
    if [ $(phpenv version-name) == '8.0' ]; then
      travis_retry composer update --ignore-platform-reqs
    fi

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - |
    if [ $(phpenv version-name) != '8.0' ]; then
      ./vendor/bin/phpcs --standard=PSR2 ./src/
    fi

after_script:
  - php ./vendor/bin/coveralls -v

notifications:
  email: false
